import { NotFoundException } from '@nestjs/common';
import { FeePlansService } from './fee-plans.service';
import { mockRepository } from '../testing/mocks';
import type { Repository } from 'typeorm';
import type { FeePlan } from './entities/fee-plan.entity';
import type { Patent } from '../patents/entities/patent.entity';

describe('FeePlansService', () => {
  let service: FeePlansService;
  let repo: ReturnType<typeof mockRepository>;
  let patentRepo: ReturnType<typeof mockRepository>;

  beforeEach(() => {
    repo = mockRepository();
    patentRepo = mockRepository();
    service = new FeePlansService(
      repo as unknown as Repository<FeePlan>,
      patentRepo as unknown as Repository<Patent>,
    );
  });

  describe('create', () => {
    it('create + save', async () => {
      repo.create.mockImplementation((dto: unknown) => ({
        ...(dto as object),
      }));
      const out = await service.create({
        dueDate: '2030-01-01',
        amount: 100,
      });
      expect(repo.save).toHaveBeenCalled();
      expect((out as Record<string, unknown>).dueDate).toBe('2030-01-01');
    });
  });

  describe('findByFee', () => {
    it('按 createTime DESC', async () => {
      await service.findByFee(7);
      expect(repo.find).toHaveBeenCalledWith({
        where: { feeId: 7 },
        order: { createTime: 'DESC' },
      });
    });
  });

  describe('findByYear', () => {
    it('按 dueDate ASC', async () => {
      await service.findByYear(2030);
      expect(repo.find).toHaveBeenCalledWith({
        where: { planYear: 2030 },
        order: { dueDate: 'ASC' },
      });
    });
  });

  describe('update', () => {
    it('不存在 → 404', async () => {
      repo.findOneBy.mockResolvedValue(null);
      await expect(service.update(1, { amount: 1 })).rejects.toBeInstanceOf(
        NotFoundException,
      );
    });
    it('存在 → Object.assign + save', async () => {
      const e = { id: 1, amount: 10 };
      repo.findOneBy.mockResolvedValue(e);
      await service.update(1, { amount: 99 });
      expect((e as Record<string, unknown>).amount).toBe(99);
      expect(repo.save).toHaveBeenCalledWith(e);
    });
  });

  describe('remove', () => {
    it('不存在 → 404', async () => {
      repo.findOneBy.mockResolvedValue(null);
      await expect(service.remove(1)).rejects.toBeInstanceOf(NotFoundException);
    });
    it('存在 → remove 并返回', async () => {
      const e = { id: 1 };
      repo.findOneBy.mockResolvedValue(e);
      await expect(service.remove(1)).resolves.toEqual({
        deleted: true,
        id: 1,
      });
      expect(repo.remove).toHaveBeenCalledWith(e);
    });
  });

  describe('batchGenerateFromPatents', () => {
    it('专利不存在 → 跳过', async () => {
      patentRepo.findOneBy.mockResolvedValue(null);
      const out = await service.batchGenerateFromPatents(
        [1],
        2030,
        {} as never,
      );
      expect(out).toEqual({ generated: 0 });
      expect(repo.save).not.toHaveBeenCalled();
    });

    it('专利无 nextFeeDate → 跳过', async () => {
      patentRepo.findOneBy.mockResolvedValue({ id: 1, nextFeeDate: null });
      const out = await service.batchGenerateFromPatents(
        [1],
        2030,
        {} as never,
      );
      expect(out).toEqual({ generated: 0 });
    });

    it('nextFeeDate 年份不匹配 → 跳过', async () => {
      patentRepo.findOneBy.mockResolvedValue({
        id: 1,
        nextFeeDate: '2029-06-01',
        feeAmount: 100,
        deptId: 5,
      });
      const out = await service.batchGenerateFromPatents(
        [1],
        2030,
        {} as never,
      );
      expect(out).toEqual({ generated: 0 });
      expect(repo.findOne).not.toHaveBeenCalled();
    });

    it('计划已存在 → 跳过', async () => {
      patentRepo.findOneBy.mockResolvedValue({
        id: 1,
        nextFeeDate: '2030-06-01',
        feeAmount: 100,
        deptId: 5,
      });
      repo.findOne.mockResolvedValue({ id: 9 });
      const out = await service.batchGenerateFromPatents(
        [1],
        2030,
        {} as never,
      );
      expect(out).toEqual({ generated: 0 });
      expect(repo.save).not.toHaveBeenCalled();
    });

    it('匹配且不存在 → 生成', async () => {
      patentRepo.findOneBy.mockResolvedValue({
        id: 1,
        nextFeeDate: '2030-06-01',
        feeAmount: 100,
        deptId: 5,
      });
      repo.findOne.mockResolvedValue(null);
      repo.create.mockImplementation((dto: unknown) => ({
        ...(dto as object),
      }));
      const out = await service.batchGenerateFromPatents(
        [1],
        2030,
        {} as never,
      );
      expect(out).toEqual({ generated: 1 });
      const created = repo.create.mock.calls[0][0] as Record<string, unknown>;
      expect(created.planYear).toBe(2030);
      expect(created.isAutoGenerated).toBe(true);
      expect(created.planStatus).toBe('pending');
      expect(created.deptId).toBe(5);
    });
  });
});
