import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { FeePlan } from './entities/fee-plan.entity';
import { CreateFeePlanDto } from './dto/create-fee-plan.dto';
import { Patent } from '../patents/entities/patent.entity';
import type { AuthUser } from '../auth/types/auth-user.interface';

@Injectable()
export class FeePlansService {
  constructor(
    @InjectRepository(FeePlan)
    private readonly repo: Repository<FeePlan>,
    @InjectRepository(Patent)
    private readonly patentRepo: Repository<Patent>,
  ) {}

  async create(dto: CreateFeePlanDto): Promise<FeePlan> {
    const entity = this.repo.create(dto);
    return this.repo.save(entity);
  }

  findByFee(feeId: number): Promise<FeePlan[]> {
    return this.repo.find({ where: { feeId }, order: { createTime: 'DESC' } });
  }

  findByYear(year: number): Promise<FeePlan[]> {
    return this.repo.find({
      where: { planYear: year },
      order: { dueDate: 'ASC' },
    });
  }

  async update(id: number, dto: Partial<CreateFeePlanDto>): Promise<FeePlan> {
    const entity = await this.repo.findOneBy({ id });
    if (!entity) throw new NotFoundException(`缴费计划 #${id} 不存在`);
    Object.assign(entity, dto);
    return this.repo.save(entity);
  }

  async remove(id: number): Promise<{ deleted: boolean; id: number }> {
    const entity = await this.repo.findOneBy({ id });
    if (!entity) throw new NotFoundException(`缴费计划 #${id} 不存在`);
    await this.repo.remove(entity);
    return { deleted: true, id };
  }

  /**
   * 根据专利的 nextFeeDate 批量生成缴费计划。
   * 对于 nextFeeDate 落在指定年份内的每件专利，创建一条 fee_plan。
   */
  async batchGenerateFromPatents(
    patentIds: number[],
    year: number,
    _user: AuthUser,
  ): Promise<{ generated: number }> {
    let created = 0;

    for (const patentId of patentIds) {
      const patent = await this.patentRepo.findOneBy({ id: patentId });
      if (!patent || !patent.nextFeeDate) continue;

      // 判断 nextFeeDate 是否在目标年份内
      const nextYear = parseInt(patent.nextFeeDate.slice(0, 4), 10);
      if (nextYear !== year) continue;

      // 避免重复生成
      const exists = await this.repo.findOne({
        where: {
          relationType: 'patent',
          relationId: patent.id,
          dueDate: patent.nextFeeDate,
        },
      });
      if (exists) continue;

      const plan = this.repo.create({
        relationType: 'patent',
        relationId: patent.id,
        planYear: year,
        dueDate: patent.nextFeeDate,
        amount: patent.feeAmount,
        planStatus: 'pending',
        isAutoGenerated: true,
        deptId: patent.deptId,
      });
      await this.repo.save(plan);
      created++;
    }

    return { generated: created };
  }
}
