import {
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

/**
 * 缴费计划表 —— 用于按年度/专利批量生成缴费计划。
 */
@Entity('fee_plan')
export class FeePlan {
  @PrimaryGeneratedColumn({ comment: '主键ID' })
  id!: number;

  @Column({ name: 'fee_id', type: 'int', nullable: true, comment: '关联费用ID' })
  feeId!: number | null;

  @Column({ name: 'relation_type', type: 'varchar', length: 20, nullable: true, comment: '关联类型: patent / copyright' })
  relationType!: string | null;

  @Column({ name: 'relation_id', type: 'int', nullable: true, comment: '关联成果ID' })
  relationId!: number | null;

  @Column({ name: 'plan_year', type: 'int', nullable: true, comment: '计划年份' })
  planYear!: number | null;

  @Column({ name: 'due_date', type: 'varchar', length: 20, comment: '计划缴费截止日(YYYY-MM-DD)' })
  dueDate!: string;

  @Column({
    type: 'decimal',
    precision: 14,
    scale: 2,
    nullable: true,
    comment: '计划金额(元)',
  })
  amount!: number | null;

  @Column({
    name: 'plan_status',
    type: 'varchar',
    length: 30,
    default: 'pending',
    comment: 'pending / paused / generated / cancelled',
  })
  planStatus!: string;

  @Column({
    name: 'is_auto_generated',
    type: 'boolean',
    default: true,
    comment: '是否系统自动生成',
  })
  isAutoGenerated!: boolean;

  @Column({ name: 'dept_id', type: 'int', nullable: true, comment: '所属部门ID' })
  deptId!: number | null;

  @CreateDateColumn({ name: 'create_time', comment: '创建时间' })
  createTime!: Date;

  @UpdateDateColumn({ name: 'update_time', comment: '更新时间' })
  updateTime!: Date;
}
